# Generated by Django 3.0.3 on 2020-07-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekapp', '0002_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.URLField(blank=True, default='DEFAULT VALUE', max_length=400),
        ),
    ]
