# Generated by Django 3.0.3 on 2020-07-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekapp', '0003_auto_20200728_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.URLField(default=None, null=True),
        ),
    ]
