# Generated by Django 3.0.3 on 2020-07-28 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geekapp', '0004_auto_20200728_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=300)),
                ('item2', models.CharField(max_length=300)),
                ('item3', models.CharField(max_length=300)),
                ('item4', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geekapp.list'),
        ),
    ]
