# Generated by Django 3.0.3 on 2020-07-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekapp', '0006_auto_20200728_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.CharField(max_length=300),
        ),
    ]
