# Generated by Django 3.0.3 on 2020-07-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekapp', '0007_auto_20200728_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='relase_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
