# Generated by Django 3.0.3 on 2020-07-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekapp', '0008_movie_relase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='relase_date',
            field=models.DateField(default=None),
        ),
    ]
