# Generated by Django 3.0.3 on 2020-07-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekapp', '0009_auto_20200729_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='relase_date',
            field=models.DateField(),
        ),
    ]
