# Generated by Django 3.0.3 on 2020-07-29 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekapp', '0015_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='relase_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
