# Generated by Django 3.0.3 on 2020-07-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geekapp', '0016_movie_relase_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='relase_date',
            new_name='date',
        ),
    ]
